#!/usr/bin/env node
require("./setup/error-listener")();
const { program } = require("commander");
const ValueAlreadyExistsForPragmaError = require("../lib/errors/ValueAlreadyExistsForPragmaError");
const arcFile = require("../lib/arc-file");
const arcCli = require("../lib/arc-cli");

program.on("--help", () => {
  console.log("");
  console.log("Example:");
  console.log("  $ ergo add ws");
});

program.action(async () => {
  try {
    await arcFile.writePragmaAndValue({
      pragma: "ws",
      value: undefined,
    });
  } catch (err) {
    if (err instanceof ValueAlreadyExistsForPragmaError) {
      console.error(`⚠️  @ws already exists`);
    } else {
      throw err;
    }
  }

  await arcCli.init();

  console.log("✅ Added @ws");
});

program.parse(process.argv);
